const Imagens={
    fundoBemVindo: require("../assets/fundoBemVindo.png"),
    fundoLoading:require("../assets/fundoLoading.png"),
    iconLocalizacao:require("../assets/iconLocalizacao.png"),
    helpHouse:require("../assets/HelpHouseTelaLogin.png"),
    helpHouseLaranja:require("../assets/helphouseLaranja.png"),
    lupa:require("../assets/lupa3.png"),
    diarista:require("../assets/diarista.png"),
    mecanico:require("../assets/mecanico.png"),
    encanador:require("../assets/encanador.png"),
    jardineiro:require("../assets/jardineiro.png"),
    pedreiro:require("../assets/pedreiro.png"),
    eletricista:require("../assets/eletricista.png"),
    fisio:require("../assets/fisio.png"),
    personal:require("../assets/personal.png"),
    iconEnviar:require("../assets/iconEnviar.png"),
    jesus:require("../assets/jesus.jpeg"),
    iconChat:require("../assets/iconChat.png"),
    iconMais:require("../assets/iconMais.png"),
    iconHome:require("../assets/iconHome.png"),
    iconFiltro:require("../assets/iconFiltro.png"),
    fundo:require("../assets/fundo.png"),
    sep:require("../assets/palmeiras.png"),
    mancha:require("../assets/mancha.png"),
   //imgs tab bar
   iconTab: require("../assets/iconTab.png"),
   iconTab2: require("../assets/iconTab2.png"),
   iconTab3: require("../assets/iconTab3.png"),
   imgPerfil:require("../assets/imgPerfil.png"),
   imgPedido:require("../assets/iconPedido.png"),
   iconSuporte:require("../assets/suporte.png")
}
export default Imagens;