const Imagens={
    fundoBemVindo: require("../assets/fundoBemVindo.png"),
    fundoLoading:require("../assets/fundoLoading.png"),
    iconLocalizacao:require("../assets/iconLocalizacao.png"),
    helpHouse:require("../assets/HelpHouseTelaLogin.png"),
    helpHouseLaranja:require("../assets/helphouseLaranja.png"),
    lupa:require("../assets/lupa3.png"),
    diarista:require("../assets/diarista.png"),
    mecanico:require("../assets/mecanico.png"),
    encanador:require("../assets/encanador.png"),
    jardineiro:require("../assets/jardineiro.png"),
    pedreiro:require("../assets/pedreiro.png"),
    eletricista:require("../assets/eletricista.png"),
    iconEnviar:require("../assets/iconEnviar.png"),
    jesus:require("../assets/jesus.jpeg"),
    iconChat:require("../assets/iconChat.png"),
    iconMais:require("../assets/iconMais.png"),
    iconHome:require("../assets/iconHome.png"),
    iconFiltro:require("../assets/iconFiltro.png"),
    iconPerfil:require("../assets/iconPerfil.png"),
}
export default Imagens;